version: '3.8'
services:
  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d287ts63jp1c7383d87g-a/identitydb_tk9e?sslmode=require
      SPRING_DATASOURCE_USERNAME: identitydb_tk9e_user
      SPRING_DATASOURCE_PASSWORD: Bna8gpFkF1AfQxrryDqvjqKbicRWXN0t
    ports:
      - "8080:8080"
